name: Upload to Docker Hub

on:
  paths:
    - 'Dockerfile'
    - 'go.mod'
    - 'go.sum'

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: diagmatrix/maybe-better-maybe-worse:latest